services:
  # Development services
  postgres:
    image: postgres:16.3
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: minidartserver
      POSTGRES_PASSWORD: "_dNoYtn9rXJAkH4iealLgp3FloOFGZdl"
    volumes:
      - minidartserver_data:/var/lib/postgresql/data
    profiles:
      - '' # Default profile
      - dev
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "0iT1SBxgzuWOGIKuX_M8g6ARK3n2pNND"
    environment:
      - REDIS_REPLICATION_MODE=master
    profiles:
      - '' # Default profile
      - dev

  # Test services
  postgres_test:
    image: postgres:16.3
    ports:
      - '9090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: minidartserver_test
      POSTGRES_PASSWORD: "SfrJLxLYnCEv0pURcrjfzu1xj8eGEqFX"
    volumes:
      - minidartserver_test_data:/var/lib/postgresql/data
    profiles:
      - '' # Default profile
      - test
  redis_test:
    image: redis:6.2.6
    ports:
      - '9091:6379'
    command: redis-server --requirepass "CSvP2QXWXzgQmUxlSf-oD2un1r1R98Qk"
    environment:
      - REDIS_REPLICATION_MODE=master
    profiles:
      - '' # Default profile
      - test

volumes:
  minidartserver_data:
  minidartserver_test_data:
